config/routes.rb
Rails.application.routes.draw do
  resources :biotops
  resources :tags
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biotop.rb
class Biotop < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/biotops_controller.rb
class BiotopsController < ApplicationController
  before_action :set_biotop, only: [:show, :edit, :update, :destroy]

  # GET /biotops
  # GET /biotops.json
  def index
    @biotops = Biotop.all
  end

  # GET /biotops/1
  # GET /biotops/1.json
  def show
  end

  # GET /biotops/new
  def new
    @biotop = Biotop.new
  end

  # GET /biotops/1/edit
  def edit
  end

  # POST /biotops
  # POST /biotops.json
  def create
    @biotop = Biotop.new(biotop_params)

    respond_to do |format|
      if @biotop.save
        format.html { redirect_to @biotop, notice: 'Biotop was successfully created.' }
        format.json { render :show, status: :created, location: @biotop }
      else
        format.html { render :new }
        format.json { render json: @biotop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biotops/1
  # PATCH/PUT /biotops/1.json
  def update
    respond_to do |format|
      if @biotop.update(biotop_params)
        format.html { redirect_to @biotop, notice: 'Biotop was successfully updated.' }
        format.json { render :show, status: :ok, location: @biotop }
      else
        format.html { render :edit }
        format.json { render json: @biotop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biotops/1
  # DELETE /biotops/1.json
  def destroy
    @biotop.destroy
    respond_to do |format|
      format.html { redirect_to biotops_url, notice: 'Biotop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biotop
      @biotop = Biotop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biotop_params
      params.require(:biotop).permit(:event_id, :tag_id, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:edate, :etype)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:tname, :num_users)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biotops_helper.rb
module BiotopsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/biotops/_form.html.erb
<%= form_for(biotop) do |f| %>
  <% if biotop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(biotop.errors.count, "error") %> prohibited this biotop from being saved:</h2>

      <ul>
      <% biotop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %>
    <%= f.number_field :event_id %>
  </div>

  <div class="field">
    <%= f.label :tag_id %>
    <%= f.number_field :tag_id %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/biotops/edit.html.erb
<h1>Editing Biotop</h1>

<%= render 'form', biotop: @biotop %>

<%= link_to 'Show', @biotop %> |
<%= link_to 'Back', biotops_path %>

app/views/biotops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Biotops</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Tag</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @biotops.each do |biotop| %>
      <tr>
        <td><%= biotop.event_id %></td>
        <td><%= biotop.tag_id %></td>
        <td><%= biotop.description %></td>
        <td><%= link_to 'Show', biotop %></td>
        <td><%= link_to 'Edit', edit_biotop_path(biotop) %></td>
        <td><%= link_to 'Destroy', biotop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biotop', new_biotop_path %>

app/views/biotops/new.html.erb
<h1>New Biotop</h1>

<%= render 'form', biotop: @biotop %>

<%= link_to 'Back', biotops_path %>

app/views/biotops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @biotop.event_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @biotop.tag_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @biotop.description %>
</p>

<%= link_to 'Edit', edit_biotop_path(@biotop) %> |
<%= link_to 'Back', biotops_path %>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :edate %>
    <%= f.text_field :edate %>
  </div>

  <div class="field">
    <%= f.label :etype %>
    <%= f.number_field :etype %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Edate</th>
      <th>Etype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.edate %></td>
        <td><%= event.etype %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edate:</strong>
  <%= @event.edate %>
</p>

<p>
  <strong>Etype:</strong>
  <%= @event.etype %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biobio01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/_form.html.erb
<%= form_for(tag) do |f| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tname %>
    <%= f.text_field :tname %>
  </div>

  <div class="field">
    <%= f.label :num_users %>
    <%= f.number_field :num_users %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tname</th>
      <th>Num users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.tname %></td>
        <td><%= tag.num_users %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tname:</strong>
  <%= @tag.tname %>
</p>

<p>
  <strong>Num users:</strong>
  <%= @tag.num_users %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>